// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.sbelei.domain;

import org.sbelei.domain.Pizza;

privileged aspect Pizza_Roo_JavaBean {
    
    public double Pizza.getStrength() {
        return this.strength;
    }
    
    public void Pizza.setStrength(double strength) {
        this.strength = strength;
    }
    
}
